# Generated by Django 6.0.4 on 2026-04-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A Rh+', 'A Rh+'), ('A Rh-', 'A Rh-'), ('B Rh+', 'B Rh+'), ('B Rh-', 'B Rh-'), ('0 Rh+', '0 Rh+'), ('0 Rh-', '0 Rh-'), ('AB Rh+', 'AB Rh+'), ('AB Rh-', 'AB Rh-')], max_length=10, null=True, verbose_name='Kan Grubu'),
        ),
    ]
