# Generated by Django 6.0.4 on 2026-04-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('member', 'Üye'), ('admin', 'Hadim'), ('imam', 'İmam')], default='member', max_length=10, verbose_name='Kullanıcı Rolü'),
        ),
    ]
