# Generated by Django 6.0.4 on 2026-04-08 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hadith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Hadis Metni')),
                ('source', models.CharField(max_length=100, verbose_name='Kaynak Kişi (Örn: Hz. Ali)')),
                ('reference', models.CharField(max_length=200, verbose_name='Kitap Referansı')),
                ('day_of_year', models.IntegerField(help_text='Hangi gün gösterilecek?', unique=True, verbose_name='Yılın Günü (1-365)')),
            ],
            options={
                'verbose_name_plural': 'Hadisler',
                'ordering': ['day_of_year'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Soru Metni')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Anonim mi?')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Cevap')),
                ('answered_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cevaplayan Hoca')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sorulma Tarihi')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Cevaplanma Tarihi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Soran Kullanıcı')),
            ],
            options={
                'verbose_name_plural': 'İstifta Soruları',
                'ordering': ['-created_at'],
            },
        ),
    ]
