# Generated by Django 6.0.4 on 2026-04-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilim', '0002_hadith_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Gizli Soru (Sadece Profilimde Gözüksün)'),
        ),
    ]
