# Generated by Django 6.0.4 on 2026-04-08 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kampanya Adı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Hedef Miktar (₺)')),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toplanan Miktar (₺)')),
                ('icon', models.CharField(max_length=10, verbose_name='İkon (Emoji)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Kampanyalar',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miktar (₺)')),
                ('donation_type', models.CharField(choices=[('Humus', 'Humus'), ('Zekat', 'Zekat'), ('Sadaka', 'Sadaka'), ('Genel Bağış', 'Genel Bağış')], max_length=20, verbose_name='Bağış Türü')),
                ('donor_name', models.CharField(blank=True, help_text='Anonim isteniyorsa boş bırakılabilir', max_length=100, null=True, verbose_name='Bağışçı Adı')),
                ('is_successful', models.BooleanField(default=True, verbose_name='Başarılı mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='bagis.campaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bağış Kayıtları',
                'ordering': ['-created_at'],
            },
        ),
    ]
