# Generated by Django 6.0.4 on 2026-04-08 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tur Adı')),
                ('date_start', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('date_end', models.DateField(verbose_name='Bitiş Tarihi')),
                ('duration', models.CharField(help_text='Örn: 7 gün, 16 gün', max_length=50, verbose_name='Süre')),
                ('price', models.CharField(help_text='Örn: 850 $, 1.200 $', max_length=50, verbose_name='Fiyat')),
                ('total_seats', models.IntegerField(verbose_name='Toplam Kontenjan')),
                ('registered_count', models.IntegerField(default=0, verbose_name='Kayıtlı Kişi')),
                ('status', models.CharField(help_text='Örn: Kayıt Açık, Son 12 Yer, Yakında', max_length=50, verbose_name='Durum Etiketi')),
                ('status_color', models.CharField(default='badge--primary', max_length=50, verbose_name='Durum Rengi (CSS sınıfı)')),
                ('image_gradient', models.CharField(default='linear-gradient(135deg, #1a3a2a, #0D4F2B)', max_length=150, verbose_name='Arka Plan (CSS gradient)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name_plural': 'Turlar',
                'ordering': ['date_start'],
            },
        ),
        migrations.CreateModel(
            name='TourRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('passport_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pasaport No')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ek Not')),
                ('status', models.CharField(choices=[('pending', 'İnceleniyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=20, verbose_name='Kayıt Durumu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Başvuru Tarihi')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='ziyaret.tour')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tur Kayıtları',
                'ordering': ['-created_at'],
            },
        ),
    ]
