# Generated by Django 6.0.4 on 2026-04-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Genel Duyuru', 'Genel Duyuru'), ('Vefat', 'Vefat'), ('Etkinlik', 'Etkinlik')], max_length=20, verbose_name='Kategori')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('body', models.TextField(verbose_name='İçerik')),
                ('badge', models.CharField(blank=True, help_text='Örn: Yeni, Yaklaşan', max_length=50, null=True, verbose_name='Rozet')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name_plural': 'Duyurular',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Kan Bağışı', 'Kan Bağışı'), ('İş İlanları', 'İş İlanları'), ('Öğrenci Desteği', 'Öğrenci Desteği'), ('Genel Yardım', 'Genel Yardım')], max_length=30, verbose_name='Kategori')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık / İsim')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('contact_info', models.CharField(blank=True, max_length=100, null=True, verbose_name='İletişim Bilgisi')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Çözüldü mü?')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
            ],
            options={
                'verbose_name_plural': 'Yardım Talepleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
