# Generated by Django 6.0.4 on 2026-04-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('Genel Duyuru', 'Genel Duyuru'), ('Vefat', 'Vefat'), ('Etkinlik', 'Etkinlik'), ('Acil', 'Acil')], max_length=20, verbose_name='Kategori'),
        ),
    ]
